### ISSUE TITLE
Basic Functionality Enhancements

### ISSUE THREAD

**Issue by meganrenae21** [meganrenae21/life-bingo#1]
Add functionality to app to include:
- ability to delete lists
- ability to delete cards
- ability to save cards as copies (rather than overriding)

### Tasks

- [x] Create test branch "basic-functionality-enhancements" _2021.08.23_
- [x]  Add deleting list function to test branch "basic-functionality-enhancements" _2021.08.23_
- [x] Add deleting card function to test branch "basic-functionality-enhancements"  _2021.08.24_
- [x] Add saving cards as copies to test branch "basic-functionality-enhancements" _2021.08.24_
- [x] Edit readme 
- [x] Create PR and merge test branch to develop branch

**Comment by meganrenae21** [comment]
- [x]  Add deleting list function to test branch "basic-functionality-enhancements" _2021.08.23_
- [ ] Merge test branch "basic-functionality-enhancements" to dist

**Comment by meganrenae21** [comment]
Completed -- develop branch at v0.2.1
